[build]
  publish = "public"
  command = "hugo --minify --gc"

[build.environment]
  HUGO_VERSION = "0.109.0"

[context.deploy-preview]
  command = "hugo --gc -b $DEPLOY_PRIME_URL --buildFuture --buildDrafts"

[context.branch-deploy]
  command = "hugo --minify --gc -b $DEPLOY_PRIME_URL"

[[headers]]
  for = "/*" # This defines which paths this specific [[headers]] block will cover.

[headers.values]
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
  Referrer-Policy = "same-origin"
  Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
  X-Content-Type-Options = "nosniff"
  Permissions-Policy = "geolocation=(self)"
  # Content-Security-Policy = "default-src 'self'; script-src 'self' https://*.netlify.app; style-src 'self' https://*.netlify.app https://fonts.googleapis.com; object-src 'none'; base-uri 'self'; connect-src 'self'; font-src 'self' https://cdnjs.cloudflare.com https://fonts.gstatic.com; frame-src 'self' https://app.netlify.com; img-src 'self' https://assets.podhome.fm https://www.buzzsprout.com; manifest-src 'self'; media-src 'self' https://*.podhome.fm https://op3.dev;"

# Suggestion from
# https://chrisshort.net/from-git-submodule-to-hugo-modules-using-netlify/
  # [build.processing]
  #   skip_processing = true