name: Approve Feed Parser Automatic PR

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Approve pull request
      if: github.actor == 'genebean'
      uses: andrewmusgrave/automatic-pull-request-review@0.0.5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        event: APPROVE
        body: 'Thank you robot friend 🎊'
