name: Run Feed Parser

on:
  workflow_dispatch:
  schedule:
    - cron: '30 10 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r scripts/requirements.txt
    - name: Run rss parser
      run: |
        python scripts/feed-parser.py
    - name: Check if there are changes
      id: changes
      run: |
        if output=$(git status --porcelain) && [ -z "$output" ]; then
          echo "changed=0" >> $GITHUB_OUTPUT
        else
          echo "changed=1" >> $GITHUB_OUTPUT
        fi
    - uses: EndBug/add-and-commit@v9
      if: steps.changes.outputs.changed == 1
      with:
        add: content/english
        message: 'Adding new content from rss feed'
        push: true
        new_branch: automation/feed-parser-action
        committer_name: GitHub Actions
        committer_email: 41898282+github-actions[bot]@users.noreply.github.com
    - name: pull-request
      if: steps.changes.outputs.changed == 1
      uses: repo-sync/pull-request@v2
      with:
        source_branch: 'automation/feed-parser-action'
        destination_branch: 'main'
        pr_label: 'automation'
        github_token: ${{ secrets.GITHUB_TOKEN }}
