name: Run Feed Parser

on:
  workflow_dispatch:
  schedule:
    - cron: '15 5 * * *'  # every day at 5:15am

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r scripts/requirements.txt
    - name: Run rss parser
      run: |
        python scripts/feed-parser.py
    - name: Check if there are changes
      id: changes
      uses: UnicornGlobal/has-changes-action@v1.0.11
    - uses: EndBug/add-and-commit@v9
      if: steps.changes.outputs.changed == 1
      with:
        add: content/english
        message: 'Adding new content from rss feed'
        push: true
        new_branch: feed-parser-action
        committer_name: GitHub Actions
        committer_email: 41898282+github-actions[bot]@users.noreply.github.com
    - name: pull-request
      if: steps.changes.outputs.changed == 1
      uses: repo-sync/pull-request@v2
      with:
        source_branch: 'feed-parser-action'
        destination_branch: 'main'
        github_token: ${{ secrets.GITHUB_TOKEN }}
